export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';

export const POST_NEW_PRODUCT = 'POST_NEW_PRODUCT';
export const POST_NEW_PRODUCT_ERROR = 'POST_NEW_PRODUCT_ERROR';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR';
